services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard-analytics
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/analytics
      - GROQ_API_KEY=${GROQ_API_KEY}
      - AGENT_MODEL=groq
      - AGENT_TEMPERATURE=0.3
      - AGENT_MAX_TOKENS=1000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - analytics_network

  postgres:
    image: postgres:17
    container_name: postgres-analytics
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - analytics_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d analytics"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  analytics_network:
    driver: bridge
